import './globals.scss'
import Context from './comp/Context'
import { Inter } from 'next/font/google'
import Footer from './comp/footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <Context>
          <header></header>
          <main>
            {children}
          </main>
          <footer>
          <Footer/>
          </footer>
        </Context>
      </body>
    </html>
  )
}
